#!/bin/sh

#install ohmyzsh
[[ ! -f ~/.oh-my-zsh ]] || git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh

paru -S ttf-meslo-nerd-font-powerlevel10k
paru -S zsh-theme-powerlevel10k-git
paru -S autojump-rs
paru -S zsh-fast-syntax-highlighting
