#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

riverctl keyboard-layout -variant abnt2 -options custom:caps_mod3,custom:hjkl_mod3_arrow br

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Return spawn foot

# Super+Q to close the focused view
riverctl map normal Super C close

riverctl map normal Control+Alt L spawn 'swaylock -l -c 000000'

riverctl map normal Super+Shift Q exit

riverctl map normal Super D spawn 'wofi --show drun --gtk-dark --lines 5 --term foot'

riverctl map normal None Print spawn "slurp | grim -g - - | swappy -f -"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J spawn "riverctl focus-view down && .config/river/blink_focused_border.sh"
#riverctl map normal Super J focus-view down
riverctl map normal Super K spawn "riverctl focus-view up && .config/river/blink_focused_border.sh"
#riverctl map normal Super K focus-view up
riverctl map normal Super H spawn "riverctl focus-view left && .config/river/blink_focused_border.sh"
#riverctl map normal Super H focus-view left
riverctl map normal Super L spawn "riverctl focus-view right && .config/river/blink_focused_border.sh"
#riverctl map normal Super L focus-view right
riverctl map normal Super Tab spawn "riverctl focus-view next && .config/river/blink_focused_border.sh"
#riverctl map normal Super Tab focus-view next

#blink focused window
riverctl map normal Super b spawn '~/.config/river/blink_focused_border.sh'


# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output with current tags
riverctl map normal Super+Shift Period send-to-output -current-tags next
riverctl map normal Super+Shift Comma send-to-output -current-tags previous
# Super+Shift+Control+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Control+Shift Period send-to-output next
riverctl map normal Super+Control+Shift Comma send-to-output previous


# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Space zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super+Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Alt L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
#riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
#riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of wideriver(1)
riverctl map normal Super+Shift H send-layout-cmd wideriver "--count 1"
riverctl map normal Super+Shift L send-layout-cmd wideriver "--count 2"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 0 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super - set-focused-tags $all_tags
riverctl map normal Super+Shift - set-view-tags $all_tags

riverctl map normal Alt Tab focus-previous-tags

# Super+Space to toggle float
riverctl map normal Super V toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +10%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -10%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    #riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    #riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -S 100'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -S 22'
done

riverctl declare-mode monitor
riverctl map normal Super M enter-mode monitor
riverctl map -release monitor Super M spawn 'notify-send "Entered Monitor mode. Options: Super+D, Super+R, Super+F"'
riverctl map monitor Super F spawn 'wlr-randr --output HDMI-A-1 --mode 1920x1080@60 --scale 1'
riverctl map -release monitor Super F enter-mode normal
riverctl map monitor Super D spawn 'wlr-randr --output HDMI-A-1 --pos "-3840,-800"'
riverctl map -release monitor Super D enter-mode normal
riverctl map monitor Super R spawn 'wlr-randr --output HDMI-A-1 --preferred --pos "1366,0"'
riverctl map -release monitor Super R enter-mode normal
riverctl map monitor Super M enter-mode normal
riverctl map -release normal Super M spawn 'notify-send "Left Monitor mode"'

riverctl default-attach-mode bottom

riverctl set-cursor-warp on-focus-change

# Set background and border color
riverctl background-color 0x002b36
#default
#riverctl border-color-focused 0x93a1a1
#cyan
#riverctl border-color-focused 0x2aa198
#magenta
riverctl border-color-focused 0xd33682
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 20 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

riverctl rule-add -app-id "firefox" ssd

riverctl rule-add -app-id "slack" tags $(((1<<3)|(1<<8)))

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
#riverctl default-layout rivertile
#rivertile -view-padding 3 -outer-padding 3 -main-location left -main-count 2 -main-ratio 0.5 &

#configure screen sharing
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

# Set the default layout generator to be wideriver and start it.
riverctl default-layout wideriver
wideriver \
    --layout                       right       \
    --layout-alt                   monocle     \
    --stack                        even        \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --border-width                 2           \
    --border-width-monocle         0           \
    --border-color-focused         "0xd33682"  \
    --border-color-focused-monocle "0x586e75"  \
    --border-color-unfocused       "0x586e75"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

riverctl focus-follows-cursor normal

# Wideriver layout toggle
riverctl map normal Super T send-layout-cmd wideriver "--layout-toggle"

waybar &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dunst &
swaybg -i Imagens/wallpapers/green-nature-26.jpg &

# set hdmi to the left
wlr-randr --output HDMI-A-1 --pos '-3840,-800'
